name: actions_toolkit_dart
version: 0.5.1
description: The GitHub ToolKit for developing GitHub Actions in Dart.
repository: https://github.com/dkrutskikh/actions-toolkit-dart
issue_tracker: https://github.com/dkrutskikh/actions-toolkit-dart/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  coverage: ^1.0.3
  dart_code_metrics: ^5.4.0
  lints: ">=1.0.0 <3.0.0"
  mocktail: ^0.3.0
  test: ^1.17.12
